// @generated by tools/scanSitePaths.ts
// Do not edit manually. Edit src/proxy-impl.ts instead.
export { proxy } from './proxy-impl';

export const config = {
  matcher: [
  "/Explorer",
  "/DataLibrary",
  "/Workspace",
  "/Workspaces",
  "/WorkspaceRequestAccess",
  "/Profile"
],
};
